spring: 
  profiles: 
    active: 
      - dev

--- 
spring: 
  profiles: dev
  application: 
    name: cloud-config-dev

server: 
  port: 8001

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: top.hhub.entities    # 所有Entity别名类所在包
  mapper-locations: 
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring: 
  application: 
    name: cloud-dept  # 对外暴露的，在eureka中的微服务的名称(大写)   有多个的话不能改
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.102.124.171:3306/clouddb1              # 数据库名称
    username: ENC(fN7JpSmX+m+Xi/K/0aCWmA==)
    password: ENC(+7NcfP4orOEHyPSLtKk2b95hEyPQPhqh)
    dbcp2: 
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url:  
      defaultZone: http://localhost:7001/eureka
  instance: 
    instance-id: cloud-dept-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info: 
  app.name: cloud
  company.name: www.hhub.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#jasypt加密的密匙
jasypt: 
  encryptor: 
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
--- 
spring: 
  profiles: test
  application: 
    name: cloud-config-test

server: 
  port: 8001

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: top.hhub.entities    # 所有Entity别名类所在包
  mapper-locations: 
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring: 
  application: 
    name: cloud-dept  # 对外暴露的，在eureka中的微服务的名称(大写)   有多个的话不能改
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.102.124.171:3306/clouddb1              # 数据库名称
    username: ENC(fN7JpSmX+m+Xi/K/0aCWmA==)
    password: ENC(+7NcfP4orOEHyPSLtKk2b95hEyPQPhqh)
    dbcp2: 
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url:  
      defaultZone: http://localhost:7001/eureka
  instance: 
    instance-id: cloud-dept-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info: 
  app.name: cloud
  company.name: www.hhub.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#jasypt加密的密匙
jasypt: 
  encryptor: 
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
